// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-_EXktAvsQngliSJ6V26odRCwuSw-Rx8',
    appId: '1:446674202041:web:1869e8b3f34af8f1579a68',
    messagingSenderId: '446674202041',
    projectId: 'chatmanager-aba56',
    authDomain: 'chatmanager-aba56.firebaseapp.com',
    storageBucket: 'chatmanager-aba56.appspot.com',
    measurementId: 'G-53YD9MP6PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRT24ciXCMo5mnzkPzoK-2NlqJpYFxJbo',
    appId: '1:446674202041:android:63180c5ef42dce8f579a68',
    messagingSenderId: '446674202041',
    projectId: 'chatmanager-aba56',
    storageBucket: 'chatmanager-aba56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBebpiFfne8S-kGT4zvmzT_4HGIOaxzL-M',
    appId: '1:446674202041:ios:50b0a55211193fe6579a68',
    messagingSenderId: '446674202041',
    projectId: 'chatmanager-aba56',
    storageBucket: 'chatmanager-aba56.appspot.com',
    iosClientId: '446674202041-j8cjv9ldljuf9hkf3nqafbv5jjond3cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBebpiFfne8S-kGT4zvmzT_4HGIOaxzL-M',
    appId: '1:446674202041:ios:50b0a55211193fe6579a68',
    messagingSenderId: '446674202041',
    projectId: 'chatmanager-aba56',
    storageBucket: 'chatmanager-aba56.appspot.com',
    iosClientId: '446674202041-j8cjv9ldljuf9hkf3nqafbv5jjond3cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatmanager',
  );
}
